
#' Construct a smoother using a GMRF smoothing prior
#'
#' This function is used internally in mgcv when fitting a smoother 
#' of type gmrf.  More details to be added.
#'
#' @param object a smooth specification object, usually generated by a term
#'              `s(...,bs="gmrf", penalty = list(Q = ...))'. `x' is a factor
#'          variable giving labels for the nodes in the GMRF graph, and the `xt'
#'          argument is obligatory: see details.
#' @param data a list containing just the data (including any `by' variable)
#'          required by this term, with names corresponding to
#'          `object$term' (and `object$by'). The `by' variable is the
#'          last element.
#' @param knots not used.
#' @return An object of class `"gmrf.smooth"'.
#' @examples
#' require(gmrf)
#' n <- 100
#' set.seed(2)
#' Q <- getQrw(100, order = 2)
#' x <- simQ(exp(1) * Q)
#' y <- x + rnorm(n) * 3
#' ## set up variables for smoothing
#' id <- 1:length(x)
#' rownames(Q) <- colnames(Q) <- id
#' ## fit an RW2 smoother
#' g1 <- gam(y ~ s(id, bs = "gmrf", xt = list(penalty = Q)), method="REML")
#' summary(g1)
#' plot(id, y)
#' lines(id, x, col = "blue", lwd = 2)
#' lines(id, fitted(g1), col = "red", lwd = 2)
#' sefit <- predict(g1, se = TRUE) $ se.fit
#' lines(id, fitted(g1) + 2*sefit, col = "red", lty = 2)
#' lines(id, fitted(g1) - 2*sefit, col = "red", lty = 2)
#' ## alternative...
#' ## g1 <- gam(y ~ s(id, bs = "mrf", xt = list(penalty = unname(Q))), knots = list(id = paste(id)), method="REML")
#' @export
smooth.construct.gmrf.smooth.spec <- function(object, data, knots) {
    k <- rownames(object$xt$penalty)
    knots <- list()
    knots[[object $ term]] <- k

    smooth.construct.mrf.smooth.spec(object, data, knots = knots)
}

